# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  code-style-express:
    name: Run style checks for Express server

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14 ]

    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Run ESLint for Express
        run: yarn run style:lint

      - name: Run Prettier for Express
        run: yarn run style:prettier

  code-style-vue:
    name: Run style checks for Vue.js app

    runs-on: ${{ matrix.os }}

    defaults:
        run:
            working-directory: ./client

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Run ESLint for Vue.js
        run: yarn run style:lint

      - name: Run Prettier for Vue.js
        run: yarn run style:prettier

  testing:
    name: Run tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14 ]
        mongodb-version: [ 4.6 ]

    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize environment variables
        run: cp -n ./env.template ./.env

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@docker-network
        with:
          mongodb-port: 27017
          mongodb-db: handshake

      - name: Install packages
        run: yarn

      - name: Run tests
        run: yarn run start:test
        env:
          MONGODB_URI: mongodb://localhost:27017/handshake

  build-vue:
    name: Build Vue.js app
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install packages
        run: yarn

      - name: Build Vue.js app
        run: yarn run build